In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv("Wine.csv")
df.sample(5)

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
45     14.21        4.04  2.44          18.9        111           2.85   
10     14.10        2.16  2.30          18.0        105           2.95   
4      13.24        2.59  2.87          21.0        118           2.80   
158    14.34        1.68  2.70          25.0         98           2.80   
113    11.41        0.74  2.50          21.0         88           2.48   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
45         2.65                  0.30             1.25             5.24  0.87   
10         3.32                  0.22             2.38             5.75  1.25   
4          2.69                  0.39             1.82             4.32  1.04   
158        1.31                  0.53             2.70            13.00  0.57   
113        2.01                  0.42             1.44             3.08  1.10   

     OD280  Proline  Customer_Segment  
45    3.33     1080                 1  
10    3.17     1510                 1  
4     2.93      735                 1  
158   1.96      660                 3  
113   2.31      434                 2

In [5]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [6]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_test

array([[ 9.38847070e-01, -6.32166068e-01, -4.35010303e-01,
        -9.19695615e-01,  1.26324041e+00,  5.59998633e-01,
         9.77754158e-01, -1.20637533e+00,  2.36680192e-02,
         3.39284695e-01, -1.45574805e-01,  8.52295413e-01,
         1.04940526e+00],
       [-2.42263344e-01,  2.67579163e-01,  4.20859365e-01,
         7.12764102e-01,  8.40672358e-01, -1.27747161e+00,
        -6.05828120e-01, -9.70634096e-01, -5.87397203e-01,
         2.42611713e+00, -2.06608025e+00, -1.55017035e+00,
        -8.66598582e-01],
       [-7.64438475e-01, -1.11802849e+00, -7.69915825e-01,
        -1.61767889e-01, -9.20027861e-01,  2.03653722e+00,
         1.18341419e+00, -1.36353615e+00,  4.48018868e-01,
        -2.50930538e-01,  1.16386073e+00,  3.94021597e-01,
        -1.06480588e+00],
       [ 7.15057728e-01, -5.78181354e-01,  3.46435916e-01,
         2.75498106e-01,  1.12238439e+00,  1.15061407e+00,
         8.54358136e-01, -1.28495574e+00,  1.43251284e+00,
         5.07917619e-01,  1.16312302e

In [22]:
from sklearn.decomposition import PCA
pca = PCA(n_components =3)
X_train1 = pca.fit_transform(X_train)
X_test1 = pca.transform(X_test)
X_train1

array([[-2.17884511e+00, -1.07218467e+00,  7.25656631e-02],
       [-1.80819239e+00,  1.57822344e+00,  8.96476572e-03],
       [ 1.09829474e+00,  2.22124345e+00, -1.09329403e-01],
       [-2.55584748e+00, -1.66210369e+00, -1.94662741e-01],
       [ 1.85698063e+00,  2.41573166e-01, -1.00300685e+00],
       [ 2.58288576e+00, -1.37668170e+00, -1.47327363e+00],
       [ 8.72876119e-01,  2.25618512e+00, -1.72526292e-01],
       [-4.18384029e-01,  2.35415681e+00,  1.48519692e+00],
       [-3.04977245e-01,  2.27659433e+00, -1.06177089e+00],
       [ 2.14082532e+00, -1.10052871e+00,  1.98193318e-01],
       [-2.98136465e+00, -2.47159183e-01,  1.13626102e+00],
       [ 1.96188242e+00,  1.25407738e+00, -4.17714193e-01],
       [-2.16177795e+00, -9.75966550e-01,  1.46325283e+00],
       [ 2.21976084e+00, -2.39507167e+00, -8.20612727e-01],
       [-2.30179529e+00, -2.05791962e-01,  8.02289900e-01],
       [-3.00953827e+00, -2.79141212e-01,  9.33830035e-01],
       [ 2.63443473e+00, -8.68313119e-01

In [23]:
X_test1

array([[ 2.20685211e+00, -1.02850086e+00,  1.03796364e+00],
       [-2.53651962e+00, -1.83644227e+00,  4.82303646e-01],
       [ 2.19183305e+00,  1.81240519e+00, -9.05607041e-02],
       [ 2.51489251e+00, -1.38907803e+00, -4.59264439e-01],
       [-3.47991313e-01,  5.25397912e-01, -5.43680847e-01],
       [ 1.44174066e+00, -2.89674514e-01, -5.12236186e+00],
       [ 2.11892046e+00, -1.62960181e+00, -1.16456308e-01],
       [-3.06045961e+00, -6.70950629e-01,  8.36930388e-02],
       [-2.35436876e-01,  2.16810201e+00,  4.35578266e-01],
       [-1.21230749e+00,  2.12204944e+00, -8.82238835e-03],
       [-2.20706720e+00, -2.61457262e-01,  8.96408192e-01],
       [-4.19759580e+00, -5.36505538e-01,  1.31591239e+00],
       [ 3.11063501e+00, -2.26380692e+00,  5.96514154e-01],
       [ 2.39878282e+00,  1.29482006e+00,  1.84077659e-01],
       [-2.16102953e+00, -1.95327620e+00, -7.54285028e-01],
       [ 9.26627235e-01,  3.35678339e+00,  3.04943214e-01],
       [ 1.96950425e+00, -1.65130081e+00

In [24]:
#training model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
classifier1 = LogisticRegression()
classifier1.fit(X_train1, y_train)

LogisticRegression()

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
1.0


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred1 = classifier1.predict(X_test1)
cm1 = confusion_matrix(y_test, y_pred1)
print(cm1)
print(accuracy_score(y_test, y_pred1))

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
1.0


In [27]:
#applyinh LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components =2)
X_train2 = lda.fit_transform(X_train, y_train)
X_test2 = lda.transform(X_test)

In [29]:
X_test2

array([[ 3.83960313,  1.54567265],
       [-5.24601727,  1.72358501],
       [ 0.66064228, -3.32231072],
       [ 2.16667061,  1.0147427 ],
       [ 0.16079996, -1.27171643],
       [ 5.31374258, -2.22014536],
       [ 4.78386714,  3.11508054],
       [-5.55863966,  0.88556084],
       [ 1.29772139, -2.40714074],
       [-0.53068371, -2.37759837],
       [-2.36900593,  1.81859204],
       [-5.14502202,  1.88061526],
       [ 5.27947032,  3.32510044],
       [ 2.70452577, -2.61522323],
       [-4.32314426,  2.14569837],
       [ 0.65835601, -4.67751669],
       [ 4.07332713,  1.95266123],
       [ 6.55291385,  4.01098911],
       [-2.40020179, -1.14618328],
       [ 5.14219986,  2.02120623],
       [ 2.46475469, -2.81225673],
       [ 2.5190649 ,  1.07965428],
       [ 1.79798575,  0.47987658],
       [ 1.43423986, -2.41298601],
       [-1.11433225, -0.98310413],
       [-0.28604133, -2.81262488],
       [ 1.21198193, -2.73115246],
       [-0.84900431, -3.34996047],
       [ 1.03105294,

In [30]:
#training model
from sklearn.linear_model import LogisticRegression
classifier2 = LogisticRegression()
classifier2.fit(X_train2, y_train)

LogisticRegression()

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred2 = classifier2.predict(X_test2)
cm2 = confusion_matrix(y_test, y_pred2)
print(cm2)
print(accuracy_score(y_test, y_pred2))

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
1.0


In [32]:
#Kernal PCA

In [33]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components=2, kernel ='rbf') #rbf=radial basis function 
X_train3 = kpca.fit_transform(X_train)
X_test3 = kpca.transform(X_test)

In [34]:
X_train3

array([[ 0.46540697, -0.23434556],
       [ 0.28634907,  0.30478225],
       [-0.12087501,  0.42663032],
       [ 0.57159263, -0.37316625],
       [-0.43039305,  0.07809796],
       [-0.44459221, -0.24595665],
       [-0.11432031,  0.50518271],
       [ 0.07099744,  0.48515601],
       [ 0.05246047,  0.51561154],
       [-0.44388392, -0.2020732 ],
       [ 0.51046787, -0.16345162],
       [-0.24377084,  0.21478452],
       [ 0.39119987, -0.22116164],
       [-0.4506256 , -0.35935991],
       [ 0.43734173, -0.11969387],
       [ 0.54556552, -0.18719483],
       [-0.50029209, -0.20833233],
       [ 0.10854094, -0.16990509],
       [-0.55629186, -0.09500493],
       [-0.00540376,  0.53316736],
       [ 0.43495067, -0.37232317],
       [ 0.50089353, -0.17762903],
       [-0.16748775,  0.13036677],
       [ 0.52942286, -0.15694334],
       [ 0.51104775, -0.36377716],
       [-0.34809893,  0.00517757],
       [ 0.44901155, -0.03030262],
       [ 0.3578409 ,  0.02884606],
       [-0.13740548,

In [35]:
#training model
from sklearn.linear_model import LogisticRegression
classifier3 = LogisticRegression()
classifier3.fit(X_train3, y_train)

LogisticRegression()

In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred3 = classifier3.predict(X_test3)
cm3 = confusion_matrix(y_test, y_pred3)
print(cm3)
print(accuracy_score(y_test, y_pred3))

[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
1.0
